model:
  name: "microsoft/Phi-3.5-mini-instruct"
  max_length: 2048
  trust_remote_code: true

lora:
  r: 16
  lora_alpha: 32
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  output_dir: "./results"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  optim: "paged_adamw_32bit"
  save_steps: 500
  logging_steps: 25
  learning_rate: 2.0e-4
  weight_decay: 0.001
  fp16: false
  bf16: true
  max_grad_norm: 0.3
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: true
  lr_scheduler_type: "cosine"
  report_to: "wandb"

quantization:
  load_in_4bit: true
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: false

data:
  train_dataset: "./data/processed/train_dataset.json"
  eval_dataset: "./data/processed/eval_dataset.json"
  max_seq_length: 2048
  train_split: 0.9
  seed: 42

evaluation:
  evaluation_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  load_best_model_at_end: true